[env:m5papers3]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino
monitor_speed = 115200
board_build.arduino.memory_type = qio_opi
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.flash_size = 16MB
board_build.partitions = custom_16MB.csv
board_build.filesystem = spiffs
build_flags = 
    -DBOARD_HAS_PSRAM
    -DESP32S3
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -mfix-esp32-psram-cache-issue
    -DCONFIG_SPIRAM_USE=1
    -DCORE_DEBUG_LEVEL=2
lib_deps =
    m5stack/M5Unified@0.2.11
    bblanchon/ArduinoJson@^6.21.0
    ayushsharma82/ElegantOTA@^3.1.7
